# Generated by Django 5.2.4 on 2025-07-16 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^(\\+?7|\\+?\\d{3}?)?(?:\\(?(\\d{3})\\)?|(\\d{3}))[-.\\s]?((\\d{3})|(\\d{4}))[-.\\s]?(\\d{4})$')], verbose_name='Номер телефона'),
        ),
    ]
