# Generated by Django 5.2.3 on 2025-07-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ban',
            field=models.BooleanField(default=False, verbose_name='Бан'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
