# Generated by Django 5.2.4 on 2025-07-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('price_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_basic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField()),
                ('views', models.IntegerField()),
                ('article_uniq', models.CharField(unique=True)),
            ],
        ),
    ]
